"""
Django settings for inventory_backend project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import secrets
import sys
from pathlib import Path
from urllib.parse import parse_qs, urlparse

from dotenv import load_dotenv

try:
    import dj_database_url
except Exception:  # pragma: no cover
    dj_database_url = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load environment variables from backend/.env if present
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

_debug_env = os.getenv("DJANGO_DEBUG", "true").strip().lower()
DEBUG = _debug_env == "true"

_secret_key_env = os.getenv("SECRET_KEY", "").strip()
if _secret_key_env:
    SECRET_KEY = _secret_key_env
else:
    if DEBUG:
        SECRET_KEY = "django-insecure-o3ozzyyf4mz$=7)1@9dp3(r!=o43wzgomv%3j5zahwd7n*8d6j"
    else:
        # Production safety net: generate a strong random key instead of
        # crashing the app. This avoids 500s on /admin when the Render env var
        # wasn't configured.
        # Note: Sessions/signed cookies will be invalidated on restart.
        SECRET_KEY = secrets.token_urlsafe(64)
        print(
            "WARNING: SECRET_KEY is not set; generated a random SECRET_KEY for this process. "
            "Set SECRET_KEY in your environment for stable admin sessions.",
            file=sys.stderr,
        )

_allowed_hosts_env = os.getenv("ALLOWED_HOSTS", "").strip()
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]
else:
    ALLOWED_HOSTS = [
        "localhost",
        "127.0.0.1",
        "0.0.0.0",
    ]


# Security hardening for production (Render sets DJANGO_DEBUG=false)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "true").strip().lower() == "true"

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS: safe default for HTTPS-only deployments.
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'corsheaders',

    # Local
    'inventory.apps.InventoryConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'inventory.middleware.LogUnhandledExceptionsMiddleware',
    'inventory.middleware.EnsureDefaultAdminOnceMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Ensure request exceptions are visible in Render logs.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        }
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": True,
        },
    },
}

ROOT_URLCONF = 'inventory_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventory_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Render / production: prefer DATABASE_URL if provided (typically Postgres)
_database_url = os.getenv("DATABASE_URL", "").strip()
if _database_url and dj_database_url is not None:
    _parsed_db_url = urlparse(_database_url)
    _db_host = (_parsed_db_url.hostname or "").lower()
    _db_scheme = (_parsed_db_url.scheme or "").lower()
    _db_query = parse_qs(_parsed_db_url.query)

    _is_postgres = _db_scheme in {"postgres", "postgresql"}
    _is_supabase = "supabase" in _db_host
    _is_supabase_pooler = (
        _parsed_db_url.port == 6543
        or "pooler.supabase.com" in _db_host
    )

    # Supabase poolers (especially transaction poolers) don't work well with
    # long-lived connections. Default to 0 unless explicitly overridden.
    _conn_max_age_env = os.getenv("CONN_MAX_AGE")
    if _conn_max_age_env is not None and _conn_max_age_env.strip() != "":
        _conn_max_age = int(_conn_max_age_env)
    else:
        _conn_max_age = 0 if _is_supabase_pooler else 600

    DATABASES["default"] = dj_database_url.config(
        default=_database_url,
        conn_max_age=_conn_max_age,
    )

    # Supabase requires SSL. If sslmode isn't provided in the URL, default to
    # require for Supabase hosts (or honor DB_SSLMODE when set).
    if _is_postgres:
        _url_sslmode = (_db_query.get("sslmode") or [None])[0]
        _env_sslmode = os.getenv("DB_SSLMODE", "").strip() or None
        _effective_sslmode = _url_sslmode or _env_sslmode or ("require" if _is_supabase else None)
        if _effective_sslmode:
            DATABASES["default"].setdefault("OPTIONS", {})
            DATABASES["default"]["OPTIONS"].setdefault("sslmode", _effective_sslmode)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Render + Whitenoise
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    }
}

# Prevent admin/template rendering from 500'ing if a static file isn't found in
# the manifest (e.g., mis-ordered collectstatic/deploy steps).
WHITENOISE_MANIFEST_STRICT = False


# CORS
# Dev-friendly default is allow-all, but for production you should set:
#   CORS_ALLOW_ALL_ORIGINS=false
#   CORS_ALLOWED_ORIGINS=https://your-frontend.onrender.com
CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "true").lower() == "true"

_cors_allowed = os.getenv("CORS_ALLOWED_ORIGINS", "").strip()
if _cors_allowed:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_allowed.split(",") if o.strip()]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
