# Generated by GitHub Copilot on 2026-04-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_item_archived_at_item_archived_by_item_is_archived"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ["name", "id"],
                "permissions": [
                    ("can_decrypt_item_details", "Can decrypt item details"),
                ],
            },
        ),
    ]
